### ISSUE TITLE
outputs return nothing

### ISSUE THREAD

**Issue by e-moshaya** [telia-oss/terraform-aws-acm-certificate#9]
Hi,

I'm using your module and on latest version 1.0.0. However, both wildcard_arn and arn outputs references return nothing...

module "acm_request_certificate" {
  source              = "telia-oss/acm-certificate/aws"
  version             = "1.0.0"
  zone_id             = "${aws_route53_zone.public.zone_id}"
  domain              = "${aws_route53_record.public.name}.domain.net"
  create_wildcard     = "false"
  wait_for_validation = "false"

  tags = "${merge(
    local.common_tags
  )}"
}

Outputs as follows both return nothing:

output "acm_request_certificate_arn" {
  value = "${module.acm_request_certificate.arn}"
}

output "acm_request_certificate_wildcard_arn" {
  value = "${module.acm_request_certificate.wildcard_arn}"
}

acm_request_certificate_arn = 
acm_request_certificate_wildcard_arn =

**Comment by colincoleman** [comment]
That is the expected behaviour if you set `wait_for_validation = "false"`.  If you set `wait_for_validation = "true"` then the terraform script will wait until the validation is complete and the certificates are created before returning with the ARNs.  With wait_for_validation = "false" the script completes once the request is made before the ARNs are known.

**Comment by e-moshaya** [comment]
thanks @colincoleman I can confirm setting wait_for_validation to true returns the arn output I need. closing this case now
